name: Create Release #
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: install
        run: npm install
      - name: test
        run: npm run test --passWithNoTests --coverage
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
      
